name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t laurence33/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true laurence33/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Debug AWS Secrets
        run: |
          echo "AWS Access Key Length: ${#AWS_ACCESS_KEY_ID}"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APP_NAME }}
          environment_name: ${{ env.EB_ENV_NAME }}
          existing_bucket_name: ${{ env.EB_BUCKET_NAME }}
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
